---
output:
  pdf_document: default
  html_document: default
---
# Supplemental Tables {#SITable}

## [Table S1](https://github.com/interactivereport/CellDepot/blob/gh-pages/bookdown/S1.csv) - Comparsion matrix of web portal tools {-}
```{r, echo=FALSE}
library(kableExtra)
df <- read.csv("S1.csv")
df %>%
  kbl() %>%
  kable_classic(full_width = F, html_font = "Cambria") %>%
  scroll_box(width = "100%")
```
Note: The criteria for query search and data analysis explorer please see Table S2 and S3.

## [Table S2](https://github.com/interactivereport/CellDepot/blob/gh-pages/bookdown/S2.csv) - Criterion for query search {-}
```{r, echo=FALSE}
library(kableExtra)


df <- read.csv("S2.csv")
df %>%
  kbl() %>%
  kable_classic(full_width = F, html_font = "Cambria") %>%
  scroll_box(width = "100%")
```

## [Table S3](https://github.com/interactivereport/CellDepot/blob/gh-pages/bookdown/S3.csv) - Criterion for data analysis explorer {-}
```{r, echo=FALSE}
library(kableExtra)
df <- read.csv("S3.csv")
df %>%
  kbl() %>%
  kable_classic(full_width = F, html_font = "Cambria") %>%
  scroll_box(width = "100%")
```

## [Table S4](https://github.com/interactivereport/CellDepot/blob/gh-pages/bookdown/S4.csv) - Project metadata captured in CellDepot {-}
```{r, echo=FALSE}
library(kableExtra)
df <- read.csv("S4.csv")
df %>%
  kbl() %>%
  kable_classic(full_width = F, html_font = "Cambria") %>%
  scroll_box(width = "100%")
```


